In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('Student.xlsx')
pd.set_option("display.max_columns", None)

In [3]:
df.shape

(3400, 56)

In [4]:
df.info()
df.drop('STUDENT IDENTIFIER', axis = 1, inplace = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 56 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STUDENT IDENTIFIER        3400 non-null   int64
 1   STDNT_AGE                 3400 non-null   int64
 2   STDNT_GENDER              3400 non-null   object
 3   STDNT_BACKGROUND          3400 non-null   object
 4   IN_STATE_FLAG             3400 non-null   object
 5   INTERNATIONAL_STS         3400 non-null   object
 6   STDNT_MAJOR               3400 non-null   object
 7   STDNT_MINOR               3400 non-null   object
 8   STDNT_TEST_ENTRANCE1      1106 non-null   float64
 9   STDNT_TEST_ENTRANCE2      2492 non-null   float64
 10  STDNT_TEST_ENTRANCE_COMB  2882 non-null   float64
 11  FIRST_TERM                3400 non-null   int64
 12  CORE_COURSE_NAME_1_F      3400 non-null   object
 13  CORE_COURSE_GRADE_1_F     3400 non-null   object
 14  CORE_COURSE_NAME_2_F      3301 non-null   object
 15  CORE_COURSE_GRADE_2_F     3301 non-null   object
 16  CORE_COURSE_NAME_3_F      2835 non-null   object
 17  CORE_COURSE_GRADE_3_F     2835 non-null   object
 18  CORE_COURSE_NAME_4_F      1803 non-null   object
 19  CORE_COURSE_GRADE_4_F     1803 non-null   object
 20  CORE_COURSE_NAME_5_F      645 non-null    object
 21  CORE_COURSE_GRADE_5_F     645 non-null    object
 22  CORE_COURSE_NAME_6_F      128 non-null    object
 23  CORE_COURSE_GRADE_6_F     128 non-null    object
 24  SECOND_TERM               3400 non-null   int64
 25  CORE_COURSE_NAME_1_S      3243 non-null   object
 26  CORE_COURSE_GRADE_1_S     3168 non-null   object
 27  CORE_COURSE_NAME_2_S      2961 non-null   object
 28  CORE_COURSE_GRADE_2_S     2961 non-null   object
 29  CORE_COURSE_NAME_3_S      2362 non-null   object
 30  CORE_COURSE_GRADE_3_S     2362 non-null   object
 31  CORE_COURSE_NAME_4_S      1355 non-null   object
 32  CORE_COURSE_GRADE_4_S     1355 non-null   object
 33  CORE_COURSE_NAME_5_S      450 non-null    object
 34  CORE_COURSE_GRADE_5_S     450 non-null    object
 35  CORE_COURSE_NAME_6_S      81 non-null     object
 36  CORE_COURSE_GRADE_6_S     81 non-null     object
 37  HOUSING_STS               3400 non-null   object
 38  RETURNED_2ND_YR           3400 non-null   int64
 39  DISTANCE_FROM_HOME        3375 non-null   float64
 40  HIGH_SCHL_GPA             3347 non-null   float64
 41  HIGH_SCHL_NAME            3399 non-null   object
 42  FATHER_HI_EDU_CD          2968 non-null   float64
 43  FATHER_HI_EDU_DESC        3400 non-null   object
 44  MOTHER_HI_EDU_CD          2911 non-null   float64
 45  MOTHER_HI_EDU_DESC        3400 non-null   object
 46  DEGREE_GROUP_CD           3400 non-null   object
 47  DEGREE_GROUP_DESC         3400 non-null   object
 48  FIRST_TERM_ATTEMPT_HRS    3400 non-null   int64
 49  FIRST_TERM_EARNED_HRS     3400 non-null   int64
 50  SECOND_TERM_ATTEMPT_HRS   3194 non-null   float64
 51  SECOND_TERM_EARNED_HRS    3191 non-null   float64
 52  GROSS_FIN_NEED            3400 non-null   int64
 53  COST_OF_ATTEND            3400 non-null   int64
 54  EST_FAM_CONTRIBUTION      3400 non-null   int64
 55  UNMET_NEED                3400 non-null   float64
dtypes: float64(10), int64(10), object(36)
memory usage: 1.5+ MB

In [5]:
df.head()

,STDNT_AGE,STDNT_GENDER,STDNT_BACKGROUND,IN_STATE_FLAG,INTERNATIONAL_STS,STDNT_MAJOR,STDNT_MINOR,STDNT_TEST_ENTRANCE1,STDNT_TEST_ENTRANCE2,STDNT_TEST_ENTRANCE_COMB,FIRST_TERM,CORE_COURSE_NAME_1_F,CORE_COURSE_GRADE_1_F,CORE_COURSE_NAME_2_F,CORE_COURSE_GRADE_2_F,CORE_COURSE_NAME_3_F,CORE_COURSE_GRADE_3_F,CORE_COURSE_NAME_4_F,CORE_COURSE_GRADE_4_F,CORE_COURSE_NAME_5_F,CORE_COURSE_GRADE_5_F,CORE_COURSE_NAME_6_F,CORE_COURSE_GRADE_6_F,SECOND_TERM,CORE_COURSE_NAME_1_S,CORE_COURSE_GRADE_1_S,CORE_COURSE_NAME_2_S,CORE_COURSE_GRADE_2_S,CORE_COURSE_NAME_3_S,CORE_COURSE_GRADE_3_S,CORE_COURSE_NAME_4_S,CORE_COURSE_GRADE_4_S,CORE_COURSE_NAME_5_S,CORE_COURSE_GRADE_5_S,CORE_COURSE_NAME_6_S,CORE_COURSE_GRADE_6_S,HOUSING_STS,RETURNED_2ND_YR,DISTANCE_FROM_HOME,HIGH_SCHL_GPA,HIGH_SCHL_NAME,FATHER_HI_EDU_CD,FATHER_HI_EDU_DESC,MOTHER_HI_EDU_CD,MOTHER_HI_EDU_DESC,DEGREE_GROUP_CD,DEGREE_GROUP_DESC,FIRST_TERM_ATTEMPT_HRS,FIRST_TERM_EARNED_HRS,SECOND_TERM_ATTEMPT_HRS,SECOND_TERM_EARNED_HRS,GROSS_FIN_NEED,COST_OF_ATTEND,EST_FAM_CONTRIBUTION,UNMET_NEED
0,18,F,BGD 1,Y,N,Undeclared,N,NaN,1150.0,1150.0,200708,ANTH 1105,A,ARTH 1100,A,ENGL 1102,A,PSYC 1101,A,NaN,NaN,NaN,NaN,200802,CHEM 1151,A,CHEM 1151L,A,COMM 1110,A,ITDS 2749,A,NaN,NaN,NaN,NaN,On Campus,0,150.0,4.00,SCHOOL 50,NaN,No Information,NaN,No Information,B,Bachelors,16,16,14.0,14.0,0,0,0,0.0
1,19,F,BGD 1,N,N,Undeclared,N,26.0,NaN,1190.0,200808,ANTH 1105,A,GERM 1002,A,ITDS 2735,A,MATH 1125,A,THEA 1100,A,POLS 1101,A,200902,ECON 2105,A,ENGL 1102,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Off Campus,1,69.0,2.89,SCHOOL 389,3.0,College/Beyond,3.0,College/Beyond,B,Bachelors,18,18,18.0,18.0,570000,1355760,785760,459300.0
2,18,M,BGD 1,Y,N,Mathematics,N,NaN,1020.0,1030.0,201008,ANTH 1105,A,ENGL 1101,A,HIST 2111,A,MATH 1111,A,SOCI 1101,A,NaN,NaN,201102,ENGL 1102,A,ENVS 1105,A,MUSC 1100,A,NaN,NaN,NaN,NaN,NaN,NaN,On Campus,1,150.0,3.39,SCHOOL 82,2.0,High School,4.0,Other/Unknown,B,Bachelors,15,15,14.0,14.0,0,0,0,0.0
3,18,M,BGD 1,Y,N,Undeclared,N,NaN,1210.0,1220.0,200708,ANTH 1107,A,COMM 1110,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200802,ENGL 1102,A,HIST 2112,A,LEAD 1705,A,MUSC 1100,A,NaN,NaN,NaN,NaN,On Campus,1,150.0,2.93,SCHOOL 180,3.0,College/Beyond,3.0,College/Beyond,B,Bachelors,13,13,14.0,14.0,0,0,0,0.0
4,18,F,BGD 1,Y,N,Art,N,NaN,1200.0,1190.0,200808,ANTH 1107,A,ARTH 1100,A,CPSC 1105,A,MATH 1111,A,NaN,NaN,NaN,NaN,200902,COMM 1110,A,ENGL 1101,A,HIST 2111,A,PSYC 1101,A,NaN,NaN,NaN,NaN,Off Campus,1,69.0,3.86,SCHOOL 2,3.0,College/Beyond,2.0,High School,B,Bachelors,12,12,12.0,12.0,835920,1355760,519840,278340.0

In [6]:
for col in df.select_dtypes('object').columns:
    print(f"Column: {col}")
    print(df[col].value_counts())
    print("-" * 40)

Column: STDNT_GENDER
STDNT_GENDER
F    2140
M    1260
Name: count, dtype: int64
----------------------------------------
Column: STDNT_BACKGROUND
STDNT_BACKGROUND
BGD 1    2082
BGD 3     947
BGD 4     139
BGD 2     106
BGD 6      94
BGD 7      19
BGD 5       8
BGD 8       5
Name: count, dtype: int64
----------------------------------------
Column: IN_STATE_FLAG
IN_STATE_FLAG
Y    3063
N     337
Name: count, dtype: int64
----------------------------------------
Column: INTERNATIONAL_STS
INTERNATIONAL_STS
N    3373
Y      27
Name: count, dtype: int64
----------------------------------------
Column: STDNT_MAJOR
STDNT_MAJOR
Undeclared                        460
Biology                           362
Early Childhood Education         190
Pre-Nursing                       177
Nursing                           164
Psychology                        155
Pre-Business                      133
Theatre Arts                      131
Music Performance                  99
Criminal Justice                   98
Music Education                    96
General Business                   85
Exercise Science                   81
Art                                75
Management                         72
Communication                      70
Political Science                  64
Chemistry                          64
English Language/Literature        60
Engineering Studies                60
Marketing                          59
Computer Science - Systems         58
Accounting                         54
Health Science                     48
Computer Science - Games           40
Joint Enrollment - Accel           35
History                            33
Applied Computer Science           32
Theatre Education                  29
English and Secondary Ed           28
Pre-Engineering/RETP               27
History and Secondary Ed           27
Mathematics                        26
Finance                            24
Management Information Systems     21
Sociology                          20
Health and Physical Education      20
Middle Grades Education            17
Music                              17
Spec Ed: Gen. Curr. - Reading      13
General Studies/AS                 12
Mathematics and Secondary Ed       11
Information Technology             10
Art Education                       9
Biology and Secondary Ed            5
Spanish                             5
French                              4
French with Teacher Cert            4
Geology                             4
Spanish with Teacher Cert           4
Early Admission - Accel             3
Chemistry and Secondary Ed          2
Earth and Space Science             2
Liberal Arts                        1
Name: count, dtype: int64
----------------------------------------
Column: STDNT_MINOR
STDNT_MINOR
N                                3160
Spanish                            26
Psychology                         19
Music                              19
Foundations of Business            15
Communication                      14
History                            13
Criminal Justice                   12
Theatre Arts                       12
Computer Science - Systems         10
Early Childhood Education           9
Mathematics                         7
Professional Writing                6
Art History                         6
Marketing                           6
English Language/Literature         5
Sociology                           5
Art                                 5
Political Science                   4
Biology                             4
Accounting                          4
Chemistry                           4
French                              4
Economics                           3
Health Science                      3
Exercise Science                    3
Computer Info. Management           3
International Business              3
Creative Writing                    2
Anthropology                        2
Asian Studies                       2
Military Sci & Adv Leadership       2
African Studies                     2
Philosophy                          2
Management                          2
Women's Studies                     1
Finance                             1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_1_F
CORE_COURSE_NAME_1_F
ENGL 1101    624
COMM 1110    278
HIST 2111    271
MATH 1111    226
CHEM 1211    202
            ...
PHYS 2311      1
ITDS 2726      1
ITDS 2727      1
ITDS 1146      1
ENGL 2111      1
Name: count, Length: 69, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_1_F
CORE_COURSE_GRADE_1_F
C          1024
B           941
D           538
F           440
A           322
NOT REP     106
INCOMPL      29
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_2_F
CORE_COURSE_NAME_2_F
ENGL 1101     736
HIST 2111     262
COMM 1110     217
MATH 1111     206
HIST 2112     139
             ...
PHYS 1325       1
THEA 1100I      1
ASTR 1305       1
ITDS 2727       1
MATH 2125       1
Name: count, Length: 74, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_2_F
CORE_COURSE_GRADE_2_F
B          1339
C           795
A           745
D           292
F           123
INCOMPL       4
NOT REP       3
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_3_F
CORE_COURSE_NAME_3_F
ENGL 1101     568
HIST 2111     176
MATH 1111     162
COMM 1110     158
POLS 1101     140
             ...
BIOL 1225K      1
ENGL 2136       1
ANTH 1107       1
PHYS 2211       1
LATN 1002       1
Name: count, Length: 74, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_3_F
CORE_COURSE_GRADE_3_F
B          1155
A          1132
C           416
D           103
F            28
INCOMPL       1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_4_F
CORE_COURSE_NAME_4_F
ENGL 1101     311
MUSC 1100     115
POLS 1101     103
COMM 1110      92
MATH 1111      89
             ...
COMM 1110I      1
ENVS 1105       1
PHYS 2311       1
GERM 1002       1
POLS 1101H      1
Name: count, Length: 68, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_4_F
CORE_COURSE_GRADE_4_F
A          1094
B           540
C           137
D            27
F             4
INCOMPL       1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_5_F
CORE_COURSE_NAME_5_F
ENGL 1101                   81
ITDS 2749                   57
MATH 1111                   47
MATH 1101                   39
MUSC 1100                   38
COMM 1110                   33
POLS 1101                   32
ITDS 2735                   30
HIST 2111                   27
PSYC 1101                   23
CHEM 1211L                  23
SPAN 1001                   19
THEA 1100                   19
CHEM 1151L                  19
CPSC 1301L                  16
MATH 1113                   15
LEAD 1705                   14
SOCI 1101                   14
HIST 2112                   11
ITDS 2748                   10
STAT 1127                    7
ECON 2106                    6
SPAN 1002                    6
MATH 1131                    5
ENGL 1102                    5
ARTH 1100                    4
CPSC 1105                    3
POLS 1101H                   3
CHEM 1211                    3
BIOL 1215K                   3
MATH 1125                    3
FREN 1001                    3
HIST 1111                    3
ECON 2105                    2
CPSC 1301                    2
ITDS 1146                    2
COMM 1110I                   2
Life and Career Planning     1
ITDS 1156                    1
POLS 2401                    1
JAPN 1001                    1
ITDS 2726                    1
PHYS 1325                    1
HIST 1112I                   1
ITDS 1145                    1
GEOL 1121                    1
FREN 1002                    1
GEOL 1110                    1
ENVS 1105I                   1
MATH 2115                    1
HIST 1112                    1
ITDS 2746                    1
CHEM 1151                    1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_5_F
CORE_COURSE_GRADE_5_F
A    502
B    111
C     27
D      5
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_6_F
CORE_COURSE_NAME_6_F
ITDS 2749               20
SOCI 1101               14
LEAD 1705               12
MATH 1111               10
ENGL 1101               10
MATH 1101                7
POLS 1101                7
MATH 1113                7
MUSC 1100                5
HIST 2112                4
PSYC 1101                4
THEA 1100                4
CHEM 1211L               3
ITDS 2735                3
MATH 1131                3
HIST 2111                2
ITDS 2748                2
COMM 1110                2
CHEM 1151L               2
SPAN 1001                2
CPSC 1301L               2
U.S. History to 1865     1
HIST 1112                1
FREN 2002                1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_6_F
CORE_COURSE_GRADE_6_F
A    110
B     14
C      3
D      1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_1_S
CORE_COURSE_NAME_1_S
ENGL 1102     627
COMM 1110     241
POLS 1101     204
HIST 2111     196
MATH 1111     187
             ...
ENGL 1101I      1
MATH 2115       1
ITDS 2727       1
POLS 1101H      1
ITDS 2748       1
Name: count, Length: 66, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_1_S
CORE_COURSE_GRADE_1_S
C          906
B          896
D          501
F          421
A          366
NOT REP     47
INCOMPL     26
Unknown      5
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_2_S
CORE_COURSE_NAME_2_S
ENGL 1102     617
COMM 1110     208
POLS 1101     183
HIST 2111     164
HIST 2112     150
             ...
COMM 1110H      1
GEOL 2225       1
POLS 1101H      1
MATH 2115       1
MATH 2125       1
Name: count, Length: 69, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_2_S
CORE_COURSE_GRADE_2_S
B          1118
A           778
C           698
D           224
F           141
INCOMPL       2
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_3_S
CORE_COURSE_NAME_3_S
ENGL 1102     405
POLS 1101     177
COMM 1110     170
MUSC 1100     138
MATH 1111     133
             ...
PHYS 1325       1
GEOL 1121L      1
FREN 2002       1
ANTH 1107       1
MATH 2115       1
Name: count, Length: 68, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_3_S
CORE_COURSE_GRADE_3_S
A          995
B          891
C          358
D           80
F           37
INCOMPL      1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_4_S
CORE_COURSE_NAME_4_S
ENGL 1102     198
POLS 1101     133
MUSC 1100      98
ITDS 2735      82
COMM 1110      68
             ...
COMM 1110H      1
BIOL 1225K      1
ITDS 1156       1
HIST 1112I      1
ENGL 1101I      1
Name: count, Length: 64, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_4_S
CORE_COURSE_GRADE_4_S
A    770
B    439
C    109
D     30
F      7
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_5_S
CORE_COURSE_NAME_5_S
MUSC 1100     44
POLS 1101     41
ITDS 2735     41
ENGL 1102     41
MATH 1111     27
THEA 1100     24
COMM 1110     18
PSYC 1101     16
SPAN 1001     16
CHEM 1151L    12
ENGL 1101     12
SOCI 1101     10
MATH 1101     10
ITDS 1145      9
ITDS 2749      9
GEOL 1121L     8
ITDS 2726      8
HIST 2111      8
HIST 2112      7
ENGL 2136      6
SPAN 1002      6
ITDS 2746      6
MATH 1113      6
CHEM 1211L     5
CPSC 1301L     5
STAT 1127      5
FREN 1001      4
LEAD 1705      4
ITDS 1146      4
ITDS 2727      4
ITDS 2748      3
ECON 2105      3
ECON 2106      3
ARTH 1100      2
MATH 1125      2
GEOL 1110      2
CPSC 1105      2
ENVS 1105      2
CHEM 1151      2
POLS 2401      2
MATH 2125      1
MATH 1132      1
HIST 1112      1
PHYS 1125      1
ITDS 1155      1
ITDS 1156      1
MATH 1131      1
FREN 1002      1
HIST 1111      1
CPSC 1301      1
BIOL 1215K     1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_5_S
CORE_COURSE_GRADE_5_S
A    303
B    119
C     25
D      2
F      1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_NAME_6_S
CORE_COURSE_NAME_6_S
POLS 1101     10
PSYC 1101      8
ENGL 1102      8
SPAN 1001      7
MUSC 1100      6
ITDS 2735      5
ITDS 2749      4
MATH 1111      3
MATH 1101      3
ENGL 1101      3
HIST 2111      3
CHEM 1151L     3
SPAN 1002      2
THEA 1100      2
LEAD 1705      2
ITDS 2746      2
STAT 1127      1
HIST 2112      1
MATH 1125      1
ITDS 2727      1
SOCI 1101      1
COMM 1110      1
CPSC 1105      1
ITDS 2748      1
CPSC 1301L     1
CHEM 1151      1
Name: count, dtype: int64
----------------------------------------
Column: CORE_COURSE_GRADE_6_S
CORE_COURSE_GRADE_6_S
A    65
B    15
C     1
Name: count, dtype: int64
----------------------------------------
Column: HOUSING_STS
HOUSING_STS
Off Campus    1981
On Campus     1419
Name: count, dtype: int64
----------------------------------------
Column: HIGH_SCHL_NAME
HIGH_SCHL_NAME
SCHOOL 11     249
SCHOOL 130    245
SCHOOL 10     238
SCHOOL 1      209
SCHOOL 2      129
             ...
SCHOOL 197      1
SCHOOL 484      1
SCHOOL 214      1
SCHOOL 329      1
SCHOOL 451      1
Name: count, Length: 439, dtype: int64
----------------------------------------
Column: FATHER_HI_EDU_DESC
FATHER_HI_EDU_DESC
High School                  1336
College/Beyond               1309
No Information                432
Other/Unknown                 226
Middle School/Junior High      97
Name: count, dtype: int64
----------------------------------------
Column: MOTHER_HI_EDU_DESC
MOTHER_HI_EDU_DESC
College/Beyond               1500
High School                  1223
No Information                489
Other/Unknown                 117
Middle School/Junior High      71
Name: count, dtype: int64
----------------------------------------
Column: DEGREE_GROUP_CD
DEGREE_GROUP_CD
B    3384
A      12
V       4
Name: count, dtype: int64
----------------------------------------
Column: DEGREE_GROUP_DESC
DEGREE_GROUP_DESC
Bachelors           3384
Associate             12
Career Associate       4
Name: count, dtype: int64
----------------------------------------

In [7]:
df.describe().loc[['min', 'max', 'mean']]

,STDNT_AGE,STDNT_TEST_ENTRANCE1,STDNT_TEST_ENTRANCE2,STDNT_TEST_ENTRANCE_COMB,FIRST_TERM,SECOND_TERM,RETURNED_2ND_YR,DISTANCE_FROM_HOME,HIGH_SCHL_GPA,FATHER_HI_EDU_CD,MOTHER_HI_EDU_CD,FIRST_TERM_ATTEMPT_HRS,FIRST_TERM_EARNED_HRS,SECOND_TERM_ATTEMPT_HRS,SECOND_TERM_EARNED_HRS,GROSS_FIN_NEED,COST_OF_ATTEND,EST_FAM_CONTRIBUTION,UNMET_NEED
min,16.000000,8.000000,350.000000,530.000000,200508.0,200602.0,0.000000,0.000000,0.000000,1.000000,1.000000,9.000000,0.000,2.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,-1.212072e+06
max,26.000000,32.000000,1490.000000,1510.000000,201008.0,201102.0,1.000000,5932.000000,4.000000,4.000000,4.000000,21.000000,21.000,23.000000,23.000000,2.124900e+06,2.124900e+06,5.999940e+06,1.632660e+06
mean,17.994118,20.660036,965.092295,997.758501,200777.0,200871.0,0.787353,99.825185,3.202738,2.560647,2.571281,13.985882,12.205,14.285848,12.511125,3.034025e+05,5.515335e+05,3.446899e+05,7.222052e+04

In [8]:
df.isnull().sum()

STDNT_AGE                      0
STDNT_GENDER                   0
STDNT_BACKGROUND               0
IN_STATE_FLAG                  0
INTERNATIONAL_STS              0
STDNT_MAJOR                    0
STDNT_MINOR                    0
STDNT_TEST_ENTRANCE1        2294
STDNT_TEST_ENTRANCE2         908
STDNT_TEST_ENTRANCE_COMB     518
FIRST_TERM                     0
CORE_COURSE_NAME_1_F           0
CORE_COURSE_GRADE_1_F          0
CORE_COURSE_NAME_2_F          99
CORE_COURSE_GRADE_2_F         99
CORE_COURSE_NAME_3_F         565
CORE_COURSE_GRADE_3_F        565
CORE_COURSE_NAME_4_F        1597
CORE_COURSE_GRADE_4_F       1597
CORE_COURSE_NAME_5_F        2755
CORE_COURSE_GRADE_5_F       2755
CORE_COURSE_NAME_6_F        3272
CORE_COURSE_GRADE_6_F       3272
SECOND_TERM                    0
CORE_COURSE_NAME_1_S         157
CORE_COURSE_GRADE_1_S        232
CORE_COURSE_NAME_2_S         439
CORE_COURSE_GRADE_2_S        439
CORE_COURSE_NAME_3_S        1038
CORE_COURSE_GRADE_3_S       1038
CORE_COURSE_NAME_4_S        2045
CORE_COURSE_GRADE_4_S       2045
CORE_COURSE_NAME_5_S        2950
CORE_COURSE_GRADE_5_S       2950
CORE_COURSE_NAME_6_S        3319
CORE_COURSE_GRADE_6_S       3319
HOUSING_STS                    0
RETURNED_2ND_YR                0
DISTANCE_FROM_HOME            25
HIGH_SCHL_GPA                 53
HIGH_SCHL_NAME                 1
FATHER_HI_EDU_CD             432
FATHER_HI_EDU_DESC             0
MOTHER_HI_EDU_CD             489
MOTHER_HI_EDU_DESC             0
DEGREE_GROUP_CD                0
DEGREE_GROUP_DESC              0
FIRST_TERM_ATTEMPT_HRS         0
FIRST_TERM_EARNED_HRS          0
SECOND_TERM_ATTEMPT_HRS      206
SECOND_TERM_EARNED_HRS       209
GROSS_FIN_NEED                 0
COST_OF_ATTEND                 0
EST_FAM_CONTRIBUTION           0
UNMET_NEED                     0
dtype: int64

In [9]:
threshold = 0.4  # 40%
df = df.dropna(axis=1, thresh=int((1 - threshold) * len(df)))

In [13]:
for col in df.select_dtypes('number').columns:
    df[col].fillna(df[col].mean(), inplace = True)

C:\Users\mahmo\AppData\Local\Temp\ipykernel_74632\3020785243.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace = True)

In [14]:
for col in df.select_dtypes('object').columns:
    df[col].fillna(df[col].mode()[0], inplace = True)

C:\Users\mahmo\AppData\Local\Temp\ipykernel_74632\3561820282.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace = True)

In [ ]:
df.isnull().sum().sum()
df.

np.int64(0)

In [19]:
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

label_encoders = {}
for col in df_encoded.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
    label_encoders[col] = le  

print(df_encoded.shape)

(3400, 42)

In [11]:
final_df.isnull().sum()

STDNT_AGE                               0
STDNT_TEST_ENTRANCE2                  908
STDNT_TEST_ENTRANCE_COMB              518
FIRST_TERM                              0
SECOND_TERM                             0
                                     ...
DEGREE_GROUP_CD_B                       0
DEGREE_GROUP_CD_V                       0
DEGREE_GROUP_DESC_Associate             0
DEGREE_GROUP_DESC_Bachelors             0
DEGREE_GROUP_DESC_Career Associate      0
Length: 1040, dtype: int64

In [14]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Columns: 1040 entries, STDNT_AGE to DEGREE_GROUP_DESC_Career Associate
dtypes: bool(1022), float64(9), int64(9)
memory usage: 3.8 MB

In [ ]:
for col in :
    df[col].fillna(df[col].mean(), inplace = True)

STDNT_AGE                      0
STDNT_GENDER                   0
STDNT_BACKGROUND               0
IN_STATE_FLAG                  0
INTERNATIONAL_STS              0
STDNT_MAJOR                    0
STDNT_MINOR                    0
STDNT_TEST_ENTRANCE2           0
STDNT_TEST_ENTRANCE_COMB       0
FIRST_TERM                     0
CORE_COURSE_NAME_1_F           0
CORE_COURSE_GRADE_1_F          0
CORE_COURSE_NAME_2_F          99
CORE_COURSE_GRADE_2_F         99
CORE_COURSE_NAME_3_F         565
CORE_COURSE_GRADE_3_F        565
SECOND_TERM                    0
CORE_COURSE_NAME_1_S         157
CORE_COURSE_GRADE_1_S        232
CORE_COURSE_NAME_2_S         439
CORE_COURSE_GRADE_2_S        439
CORE_COURSE_NAME_3_S        1038
CORE_COURSE_GRADE_3_S       1038
HOUSING_STS                    0
RETURNED_2ND_YR                0
DISTANCE_FROM_HOME             0
HIGH_SCHL_GPA                  0
HIGH_SCHL_NAME                 1
FATHER_HI_EDU_CD               0
FATHER_HI_EDU_DESC             0
MOTHER_HI_EDU_CD               0
MOTHER_HI_EDU_DESC             0
DEGREE_GROUP_CD                0
DEGREE_GROUP_DESC              0
FIRST_TERM_ATTEMPT_HRS         0
FIRST_TERM_EARNED_HRS          0
SECOND_TERM_ATTEMPT_HRS        0
SECOND_TERM_EARNED_HRS         0
GROSS_FIN_NEED                 0
COST_OF_ATTEND                 0
EST_FAM_CONTRIBUTION           0
UNMET_NEED                     0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import classification_report

In [14]:
x = final_df.drop('RETURNED_2ND_YR', axis = 1)
y = final_df['RETURNED_2ND_YR']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
models = {
    'GaussianNB': (GaussianNB(), {'var_smoothing': [1e-9, 1e-8, 1e-7]}),
    'MultinomialNB': (MultinomialNB(), {'alpha': [0.1, 0.5, 1.0]}),
    'BernoulliNB': (BernoulliNB(), {'alpha': [0.1, 0.5, 1.0], 'binarize': [0.0, 0.5, 1.0]})
}
best_models = {}

In [ ]:
for name, (model, params) in models.items():
    grid = GridSearchCV(model, param_grid=params, cv=5, scoring='accuracy')
    grid.fit(X_train, y_train)
    
    print(f"Best parameters for {name}: {grid.best_params_}")
    print(f"Best CV score: {grid.best_score_:.4f}")
    
    y_pred = grid.predict(X_test)
    print(f"Test set performance for {name}:")
    print(classification_report(y_test, y_pred))
    print("-" * 60)
    
    best_models[name] = grid.best_estimator_

ValueError:
All the 15 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\naive_bayes.py", line 266, in fit
    return self._partial_fit(
           ~~~~~~~~~~~~~~~~~^
        X, y, np.unique(y), _refit=True, sample_weight=sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\naive_bayes.py", line 426, in _partial_fit
    X, y = validate_data(self, X, y, reset=first_call)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 2961, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 1370, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 1107, in check_array
    _assert_all_finite(
    ~~~~~~~~~~~~~~~~~~^
        array,
        ^^^^^^
    ...<2 lines>...
        allow_nan=ensure_all_finite == "allow-nan",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 120, in _assert_all_finite
    _assert_all_finite_element_wise(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        X,
        ^^
    ...<4 lines>...
        input_name=input_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\mahmo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py", line 169, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values